# This docker-compose file is used for local development and testing.

services:
  api.monorepo-template:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    container_name: monorepo-template-api
    env_file:
      - ./apps/api/.env
      - ./apps/api/envs/.env.base
    environment:
      - DB_URL=${DB_URL}
      - API_JWT_SECRET_KEY=${API_JWT_SECRET_KEY}
      - API_JWT_REFRESH_SECRET_KEY=${API_JWT_REFRESH_SECRET_KEY}
      - API_EMAIL_USERNAME=${API_EMAIL_USERNAME}
      - API_EMAIL_PASSWORD=${API_EMAIL_PASSWORD}
      - API_AWS_SECRET_ACCESS_KEY=${API_AWS_SECRET_ACCESS_KEY}
      - API_AWS_ACCESS_KEY_ID=${API_AWS_ACCESS_KEY_ID}
    ports:
      - '3000:3000'
    restart: unless-stopped
    networks:
      - hatt_law_infra

networks:
  hatt_law_infra:
    driver: bridge
