import { MigrationInterface, QueryRunner } from 'typeorm';

export class ChangeEnumToVarcharForAllEntities1738854231741 implements MigrationInterface {
  name = 'ChangeEnumToVarcharForAllEntities1738854231741';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "old_value"`);
    await queryRunner.query(`ALTER TABLE "audit_logs" ADD "old_value" jsonb`);
    await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "new_value"`);
    await queryRunner.query(`ALTER TABLE "audit_logs" ADD "new_value" jsonb`);
    await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "action"`);
    await queryRunner.query(`DROP TYPE "public"."audit_logs_action_enum"`);
    await queryRunner.query(`ALTER TABLE "audit_logs" ADD "action" character varying(50) NOT NULL`);
    await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "table_name"`);
    await queryRunner.query(`DROP TYPE "public"."audit_logs_table_name_enum"`);
    await queryRunner.query(`ALTER TABLE "audit_logs" ADD "table_name" character varying(50) NOT NULL`);
    await queryRunner.query(`ALTER TABLE "posts" DROP COLUMN "seo_meta"`);
    await queryRunner.query(`ALTER TABLE "posts" ADD "seo_meta" jsonb`);
    await queryRunner.query(`ALTER TABLE "posts" DROP COLUMN "status"`);
    await queryRunner.query(`DROP TYPE "public"."posts_status_enum"`);
    await queryRunner.query(`ALTER TABLE "posts" ADD "status" character varying(50) NOT NULL DEFAULT 'draft'`);
    await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "seo_meta"`);
    await queryRunner.query(`ALTER TABLE "products" ADD "seo_meta" jsonb`);
    await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "status"`);
    await queryRunner.query(`DROP TYPE "public"."products_status_enum"`);
    await queryRunner.query(`ALTER TABLE "products" ADD "status" character varying(50) NOT NULL DEFAULT 'draft'`);
    await queryRunner.query(`ALTER TABLE "files" DROP COLUMN "status"`);
    await queryRunner.query(`DROP TYPE "public"."files_status_enum"`);
    await queryRunner.query(`ALTER TABLE "files" ADD "status" character varying(50) NOT NULL DEFAULT 'published'`);
    await queryRunner.query(`ALTER TABLE "categories" DROP COLUMN "seo_meta"`);
    await queryRunner.query(`ALTER TABLE "categories" ADD "seo_meta" jsonb`);
    await queryRunner.query(`ALTER TABLE "categories" DROP COLUMN "type"`);
    await queryRunner.query(`DROP TYPE "public"."categories_type_enum"`);
    await queryRunner.query(`ALTER TABLE "categories" ADD "type" character varying(50) NOT NULL DEFAULT 'post'`);
    await queryRunner.query(`ALTER TABLE "categories" DROP COLUMN "status"`);
    await queryRunner.query(`DROP TYPE "public"."categories_status_enum"`);
    await queryRunner.query(`ALTER TABLE "categories" ADD "status" character varying(50) NOT NULL DEFAULT 'published'`);
    await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "provider"`);
    await queryRunner.query(`DROP TYPE "public"."users_provider_enum"`);
    await queryRunner.query(`ALTER TABLE "users" ADD "provider" character varying(50) NOT NULL DEFAULT 'credentials'`);
    await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "auth_type"`);
    await queryRunner.query(`DROP TYPE "public"."users_auth_type_enum"`);
    await queryRunner.query(`ALTER TABLE "users" ADD "auth_type" character varying(50) NOT NULL DEFAULT 'credentials'`);
    await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "gender"`);
    await queryRunner.query(`DROP TYPE "public"."users_gender_enum"`);
    await queryRunner.query(`ALTER TABLE "users" ADD "gender" character varying(50) NOT NULL DEFAULT 'male'`);
    await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "status"`);
    await queryRunner.query(`DROP TYPE "public"."users_status_enum"`);
    await queryRunner.query(`ALTER TABLE "users" ADD "status" character varying(50) NOT NULL DEFAULT 'inactive'`);
    await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "role"`);
    await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
    await queryRunner.query(`ALTER TABLE "users" ADD "role" character varying(50) NOT NULL DEFAULT 'user'`);
    await queryRunner.query(`ALTER TABLE "faqs" DROP COLUMN "status"`);
    await queryRunner.query(`DROP TYPE "public"."faqs_status_enum"`);
    await queryRunner.query(`ALTER TABLE "faqs" ADD "status" character varying(50) NOT NULL DEFAULT 'draft'`);
    await queryRunner.query(`ALTER TABLE "contacts" DROP COLUMN "status"`);
    await queryRunner.query(`DROP TYPE "public"."contacts_status_enum"`);
    await queryRunner.query(`ALTER TABLE "contacts" ADD "status" character varying(50) NOT NULL DEFAULT 'published'`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`ALTER TABLE "contacts" DROP COLUMN "status"`);
    await queryRunner.query(`CREATE TYPE "public"."contacts_status_enum" AS ENUM('visibled', 'deleted')`);
    await queryRunner.query(`ALTER TABLE "contacts" ADD "status" "public"."contacts_status_enum" NOT NULL DEFAULT 'visibled'`);
    await queryRunner.query(`ALTER TABLE "faqs" DROP COLUMN "status"`);
    await queryRunner.query(`CREATE TYPE "public"."faqs_status_enum" AS ENUM('published', 'draft', 'deleted')`);
    await queryRunner.query(`ALTER TABLE "faqs" ADD "status" "public"."faqs_status_enum" NOT NULL DEFAULT 'draft'`);
    await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "role"`);
    await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('super_admin', 'admin', 'user')`);
    await queryRunner.query(`ALTER TABLE "users" ADD "role" "public"."users_role_enum" NOT NULL DEFAULT 'user'`);
    await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "status"`);
    await queryRunner.query(`CREATE TYPE "public"."users_status_enum" AS ENUM('active', 'inactive', 'deleted', 'blocked', 'not_verified')`);
    await queryRunner.query(`ALTER TABLE "users" ADD "status" "public"."users_status_enum" NOT NULL DEFAULT 'inactive'`);
    await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "gender"`);
    await queryRunner.query(`CREATE TYPE "public"."users_gender_enum" AS ENUM('male', 'female', 'other')`);
    await queryRunner.query(`ALTER TABLE "users" ADD "gender" "public"."users_gender_enum" NOT NULL DEFAULT 'male'`);
    await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "auth_type"`);
    await queryRunner.query(`CREATE TYPE "public"."users_auth_type_enum" AS ENUM('credentials', 'oauth')`);
    await queryRunner.query(`ALTER TABLE "users" ADD "auth_type" "public"."users_auth_type_enum" NOT NULL DEFAULT 'credentials'`);
    await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "provider"`);
    await queryRunner.query(`CREATE TYPE "public"."users_provider_enum" AS ENUM('credentials', 'facebook', 'google', 'apple')`);
    await queryRunner.query(`ALTER TABLE "users" ADD "provider" "public"."users_provider_enum" NOT NULL DEFAULT 'credentials'`);
    await queryRunner.query(`ALTER TABLE "categories" DROP COLUMN "status"`);
    await queryRunner.query(`CREATE TYPE "public"."categories_status_enum" AS ENUM('visibled', 'deleted')`);
    await queryRunner.query(`ALTER TABLE "categories" ADD "status" "public"."categories_status_enum" NOT NULL DEFAULT 'visibled'`);
    await queryRunner.query(`ALTER TABLE "categories" DROP COLUMN "type"`);
    await queryRunner.query(`CREATE TYPE "public"."categories_type_enum" AS ENUM('default', 'file', 'product', 'post')`);
    await queryRunner.query(`ALTER TABLE "categories" ADD "type" "public"."categories_type_enum" NOT NULL DEFAULT 'post'`);
    await queryRunner.query(`ALTER TABLE "categories" DROP COLUMN "seo_meta"`);
    await queryRunner.query(`ALTER TABLE "categories" ADD "seo_meta" json`);
    await queryRunner.query(`ALTER TABLE "files" DROP COLUMN "status"`);
    await queryRunner.query(`CREATE TYPE "public"."files_status_enum" AS ENUM('visibled', 'deleted')`);
    await queryRunner.query(`ALTER TABLE "files" ADD "status" "public"."files_status_enum" NOT NULL DEFAULT 'visibled'`);
    await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "status"`);
    await queryRunner.query(`CREATE TYPE "public"."products_status_enum" AS ENUM('published', 'draft', 'deleted')`);
    await queryRunner.query(`ALTER TABLE "products" ADD "status" "public"."products_status_enum" NOT NULL DEFAULT 'draft'`);
    await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "seo_meta"`);
    await queryRunner.query(`ALTER TABLE "products" ADD "seo_meta" json`);
    await queryRunner.query(`ALTER TABLE "posts" DROP COLUMN "status"`);
    await queryRunner.query(`CREATE TYPE "public"."posts_status_enum" AS ENUM('published', 'draft', 'deleted')`);
    await queryRunner.query(`ALTER TABLE "posts" ADD "status" "public"."posts_status_enum" NOT NULL DEFAULT 'draft'`);
    await queryRunner.query(`ALTER TABLE "posts" DROP COLUMN "seo_meta"`);
    await queryRunner.query(`ALTER TABLE "posts" ADD "seo_meta" json`);
    await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "table_name"`);
    await queryRunner.query(`CREATE TYPE "public"."audit_logs_table_name_enum" AS ENUM('users', 'files', 'posts', 'products', 'categories')`);
    await queryRunner.query(`ALTER TABLE "audit_logs" ADD "table_name" "public"."audit_logs_table_name_enum" NOT NULL`);
    await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "action"`);
    await queryRunner.query(`CREATE TYPE "public"."audit_logs_action_enum" AS ENUM('create', 'update', 'delete')`);
    await queryRunner.query(`ALTER TABLE "audit_logs" ADD "action" "public"."audit_logs_action_enum" NOT NULL`);
    await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "new_value"`);
    await queryRunner.query(`ALTER TABLE "audit_logs" ADD "new_value" json`);
    await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "old_value"`);
    await queryRunner.query(`ALTER TABLE "audit_logs" ADD "old_value" json`);
  }
}
