services:
  monorepo-template-db:
    container_name: monorepo-template-db
    image: postgres
    restart: always
    ports:
      - 5435:5432
    environment:
      - POSTGRES_DB=${AP_DB_NAME}
      - POSTGRES_USER=${AP_DB_USERNAME}
      - POSTGRES_PASSWORD=${AP_DB_PASSWORD}
    env_file:
      - .env
    volumes:
      - monorepo-template-posgres-db:/var/lib/postgresql/data

  monorepo-template-db-test:
    container_name: monorepo-template-db-test
    image: postgres
    restart: always
    ports:
      - 5436:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - monorepo-template-posgres-db-test:/var/lib/postgresql/data

  # monorepo-template-redis:
  #   container_name: monorepo-template-redis
  #   image: redis
  #   restart: always
  #   ports:
  #     - 6379:6379
  #   env_file:
  #     - .env

  # monorepo-template-redis-test:
  #   container_name: monorepo-template-redis-test
  #   image: redis
  #   restart: always
  #   ports:
  #     - 6380:6379
  #   env_file:
  #     - .env.test

  monorepo-template-minio:
    container_name: monorepo-template-minio
    image: minio/minio:latest
    restart: always
    ports:
      - 9000:9000 # API port
      - 9001:9001 # Console port
    environment:
      - MINIO_ROOT_USER=monorepo-template
      - MINIO_ROOT_PASSWORD=monorepo-template
    command: server --console-address ":9001" /data
    healthcheck:
      test: ['CMD', 'mc', 'ready', 'local']
      interval: 5s
      timeout: 5s
      retries: 5

  monorepo-template-api:
    build:
      context: ../../
      dockerfile: apps/api/Dockerfile
    container_name: monorepo-template-api
    ports:
      - '3500:3500'
    env_file:
      - .env
    volumes:
      - ~/monorepo-uploads:/app/apps/api/dist/uploads

volumes:
  monorepo-template-posgres-db:
  monorepo-template-posgres-db-test:
