name: Deploy Admin Portal (Stage)

on:
  push:
    branches:
      - 'create-reusable-deploy'
    paths:
      - 'apps/admin-portal/**'

jobs:
  build-and-deploy:
    uses: ./.github/workflows/deploy-reusable.yml
    with:
      app_name: admin-portal-stage
      dockerfile_path: apps/admin-portal/Dockerfile
      docker_compose_path: apps/admin-portal/docker-compose.yml
      env_file_path: apps/admin-portal/.env
      docker_host_port: 3001
      docker_container_port: 3001
      docker_compose_service: admin-portal-stage-deploy
      app_env: ${{ secrets.PORTAL_STAGE }}
