name: Deploy Admin Portal (Stage)

on:
  push:
    branches:
      - 'devops-verify-health-docker-before-deploy'
    paths:
      - 'apps/admin-portal/**'

env:
  APP_ENV: ${{ secrets.PORTAL_STAGE }}
  APP_NAME: admin-portal-stage
  DOCKER_COMPOSE_SERVICE: admin-portal-stage-deploy
  DOCKERFILE_PATH: apps/admin-portal/Dockerfile
  DOCKER_COMPOSE_PATH: apps/admin-portal/docker-compose.yml
  ENV_FILE_PATH: apps/admin-portal/.env
  DOCKER_HOST_PORT: 3001 # Change this value if your server is already run docker container with this port, using command docker ps to check it
  DOCKER_CONTAINER_PORT: 3001 # This is the app port, which command yarn start run and provided

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Pull code
        uses: actions/checkout@v3

      - name: Extract env file multi line.
        run: |
          rm -r -f ${{ env.ENV_FILE_PATH }}
          touch ${{ env.ENV_FILE_PATH }}_temp
          echo $APP_ENV| tee ${{ env.ENV_FILE_PATH }}_temp
          sed 's/ /\n/g' ${{ env.ENV_FILE_PATH }}_temp >> ${{ env.ENV_FILE_PATH }}
          rm -r -f ${{ env.ENV_FILE_PATH }}_temp

      - name: Build Docker Image
        run: |
          docker build -f ${{ env.DOCKERFILE_PATH }} -t ${{ env.APP_NAME }} .
          docker save -o ${{ env.APP_NAME }}.tar ${{ env.APP_NAME }}

      - name: Test Docker Image
        run: |
          # Run the new container temporarily
          docker run -d --name ${{ env.APP_NAME }} \
          --health-cmd="curl -f http://localhost:${{ env.DOCKER_CONTAINER_PORT}} || exit 1" \
          --health-interval=10s \
          --health-timeout=5s \
          --health-retries=3 \
          my-image:latest

          # Wait for health check
          sleep 30  # Adjust based on your health-check settings

          # Check health status
          HEALTH_STATUS=$(docker inspect --format='{{json .State.Health.Status}}' ${{ env.APP_NAME }})

          if [[ "$HEALTH_STATUS" == "\"healthy\"" ]]; then
              echo "✅ New container is healthy. Replacing old container..."
          else
              echo "❌ Error: New container is $HEALTH_STATUS. Cleaning up..."
              exit 1
          fi

      - name: Create docker-compose file
        run: |
          # Remove old docker-compose file if it exists
          rm -f ${{ env.DOCKER_COMPOSE_PATH }}
          cat << EOF > ${{ env.DOCKER_COMPOSE_PATH }}
          version: '3.8'

          services:
            ${{ env.DOCKER_COMPOSE_SERVICE }}:
              image: ${{ env.APP_NAME }}
              container_name: ${{ env.APP_NAME }}
              restart: always
              ports:
                - "${{ env.DOCKER_HOST_PORT }}:${{ env.DOCKER_CONTAINER_PORT }}"
          EOF

      - name: Copy Docker Image to ec2 use SSH Key
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.STAGE_SERVER_HOST }}
          username: ${{secrets.STAGE_SERVER_USER_NAME}}
          port: 22
          password: ${{ secrets.STAGE_SERVER_PASSWORD }}
          source: '${{ env.APP_NAME }}.tar,${{ env.DOCKER_COMPOSE_PATH }},${{ env.ENV_FILE_PATH }}'
          target: '~/${{ env.APP_NAME }}'

      - name: Executing remote ssh commands using SSH Key
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.STAGE_SERVER_HOST }}
          username: ${{secrets.STAGE_SERVER_USER_NAME}}
          port: 22
          password: ${{ secrets.STAGE_SERVER_PASSWORD }}
          script_stop: true
          script: |
            cd ~/${{ env.APP_NAME }}
            sudo docker load --input ${{ env.APP_NAME }}.tar
            sudo docker-compose -f ${{ env.DOCKER_COMPOSE_PATH }} up -d ${{ env.DOCKER_COMPOSE_SERVICE }} --force-recreate --no-build
            rm -rf ${{ env.APP_NAME }}.tar
