name: Deploy Admin API (Stage)

on:
  push:
    branches:
      - 'main'
    paths:
      - 'apps/api/**'

env:
  APP_ENV: ${{ secrets.API_STAGE }}
  APP_NAME: api-stage
  DOCKER_COMPOSE_SERVICE: monorepo-api-stage
  DOCKERFILE_PATH: apps/api/Dockerfile
  DOCKER_COMPOSE_PATH: apps/api/docker-compose.yml
  ENV_FILE_PATH: apps/api/.env
  DOCKER_HOST_PORT: 3500 # Change this value if your server is already run docker container with this port, using command docker ps to check it
  DOCKER_CONTAINER_PORT: 3500 # This is the app port, which command yarn start run and provided

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Pull code
        uses: actions/checkout@v3

      - name: Extract env file multi line.
        run: |
          rm -r -f ${{ env.ENV_FILE_PATH }}
          touch ${{ env.ENV_FILE_PATH }}_temp
          echo $APP_ENV| tee ${{ env.ENV_FILE_PATH }}_temp
          sed 's/ /\n/g' ${{ env.ENV_FILE_PATH }}_temp >> ${{ env.ENV_FILE_PATH }}
          rm -r -f ${{ env.ENV_FILE_PATH }}_temp

      - name: Build Docker Image
        run: |
          docker build -f ${{ env.DOCKERFILE_PATH }} -t ${{ env.APP_NAME }} .
          docker save -o ${{ env.APP_NAME }}.tar ${{ env.APP_NAME }}

      # For API, please choose suitable health check api route, for example http://127.0.0.1/api/v1
      - name: Test Docker Image
        run: |
          docker run -d --name ${{ env.APP_NAME }} \
          --health-cmd="curl -f http://127.0.0.1:${{ env.DOCKER_CONTAINER_PORT}}/api/v1 || exit 1" \
          --health-interval=5s \
          --health-timeout=5s \
          --health-retries=3 \
          ${{ env.APP_NAME}}:latest

          sleep 50

          HEALTH_STATUS=$(docker inspect --format='{{json .State.Health.Status}}' ${{ env.APP_NAME }})

          if [[ "$HEALTH_STATUS" == "\"healthy\"" ]]; then
              echo "✅ Test container is healthy. Ready to copy and deploy this image to your server..."
          else
              echo "❌ Error: Test container is $HEALTH_STATUS"
              echo "Fetching logs from the test container..."
              docker logs ${{ env.APP_NAME }}
              exit 1
          fi

      - name: Create docker-compose file
        run: |
          rm -f ${{ env.DOCKER_COMPOSE_PATH }}
          cat << EOF > ${{ env.DOCKER_COMPOSE_PATH }}
          version: '3.8'

          services:
            ${{ env.DOCKER_COMPOSE_SERVICE }}:
              image: ${{ env.APP_NAME }}
              container_name: ${{ env.APP_NAME }}
              restart: always
              ports:
                - "${{ env.DOCKER_HOST_PORT }}:${{ env.DOCKER_CONTAINER_PORT }}"
          EOF

      - name: Copy Docker image to server use SSH Key
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.STAGE_SERVER_HOST }}
          username: ${{secrets.STAGE_SERVER_USER_NAME}}
          port: 22
          # password: ${{ secrets.STAGE_SERVER_PASSWORD }} //NOTE: Uncomment if your VPS Server using SSH connection with password
          key: ${{ secrets.STAGE_SERVER_KEY }}
          source: '${{ env.APP_NAME }}.tar,${{ env.DOCKER_COMPOSE_PATH }},${{ env.ENV_FILE_PATH }}'
          target: '~/${{ env.APP_NAME }}'

      - name: Executing remote ssh commands using SSH Key
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.STAGE_SERVER_HOST }}
          username: ${{secrets.STAGE_SERVER_USER_NAME}}
          port: 22
          # password: ${{ secrets.STAGE_SERVER_PASSWORD }} //NOTE: Uncomment if your VPS Server using SSH connection with password
          key: ${{ secrets.STAGE_SERVER_KEY }}
          script_stop: true
          script: |
            cd ~/${{ env.APP_NAME }}
            sudo docker load --input ${{ env.APP_NAME }}.tar
            sudo docker-compose -f ${{ env.DOCKER_COMPOSE_PATH }} up -d ${{ env.DOCKER_COMPOSE_SERVICE }} --force-recreate --no-build
            rm -rf ${{ env.APP_NAME }}.tar
