name: Deploy Admin API (Stage)

on:
  push:
    branches:
      - 'main'
    paths:
      - 'apps/api/**'

jobs:
  build-and-deploy:
    uses: ./.github/workflows/deploy-reusable.yml
    with:
      app_name: api-stage
      dockerfile_path: apps/api/Dockerfile
      docker_compose_path: apps/api/docker-compose.yml
      env_file_path: apps/api/.env
      docker_host_port: 3500
      docker_container_port: 3500
      docker_compose_service: monorepo-api
      app_env: ${{ secrets.API_STAGE }}
