name: Deploy Website (Stage)

on:
  push:
    branches:
      - 'main'
    paths:
      - 'apps/website/**'

jobs:
  build-and-deploy:
    uses: ./.github/workflows/deploy-reusable.yml
    with:
      app_name: website-stage-deploy
      dockerfile_path: apps/website/Dockerfile
      docker_compose_path: apps/website/docker-compose.yml
      env_file_path: apps/website/.env
      docker_host_port: 3000
      docker_container_port: 3001
      docker_compose_service: website-stage-deploy
      app_env: ${{ secrets.WEBSITE_STAGE }}
